#!/bin/bash

for i in $(seq 1 1 10); do bin/hbgs_sigrl_list_test_129 RL_data rl_129_10 F >> test_rl_129.txt; done

for i in $(seq 1 1 10); do bin/hbgs_sigrl_list_test_129 RL_data rl_129_100 F >> test_rl_129.txt; done

for i in $(seq 1 1 10); do bin/hbgs_sigrl_list_test_129 RL_data rl_129_500 F >> test_rl_129.txt; done

for i in $(seq 1 1 10); do bin/hbgs_sigrl_list_test_129 RL_data rl_129_1000 F >> test_rl_129.txt; done
